from tkinter import *
import math as m
root =Tk()
root.title("Scientific Calculator for python project")
root.geometry("386x507")
root.minsize(386,507)
root.maxsize(386,507)
box = Entry(root, borderwidth=10,font="Times 20 bold", width=24, bg="Grey", )
box.grid( columnspan=5,  padx=10, pady=8)
def click(to_print):
    old=box.get()
    box.delete(0, END)
    box.insert(0, old+to_print)
    return
def clear():
    box.delete(0, END)
    return 
def evaluate():
    ans=box.get()
    ans=eval(ans)
    box.delete(0, END)
    box.insert(0, ans)
def bksps():
    current=box.get()
    length=len(current)-1
    box.delete(length, END)
def scop(event):
    key=event.widget
    text=key['text']
    no=box.get()
    result=''
    if text=='log':
        result=str(m.log(float(no)))
    if text=='sin':
        result=str(m.sin(float(no)))
    if text=='cos':
        result=str(m.cos(float(no)))
    if text=='tan':
        result=str(m.tan(float(no)))
    if text=='1/x':
        result=str(1/(float(no)))
    if text=='deg':
        result=str(m.degrees(float(no)))
    if text=='Sqrt':
        result=str(m.sqrt(float(no)))
    if text=='x!':
        result=str(m.factorial(float(no)))
    box.delete(0, END)
    box.insert(0, result)
dzero = Button(root, text="00",borderwidth=5, font="Times 20 bold", padx=10,pady=6,command=lambda:click('00')  )
degree = Button(root, text="deg",borderwidth=5, font="Times 20 bold" ,padx=2)
degree.bind("<Button-1>", scop)
sin= Button(root, text="sin", borderwidth=5,font="Times 20 bold",padx=6 )
sin.bind("<Button-1>", scop)
cos= Button(root, text="cos", borderwidth=5,font="Times 20 bold",padx=7)
cos.bind("<Button-1>", scop)
tan = Button(root, text="tan", borderwidth=5,font="Times 20 bold",padx=7)
tan.bind("<Button-1>", scop)
squrt = Button(root, text="Sqrt",borderwidth=5,  font="Times 20 bold",padx=0,pady=2)
squrt.bind("<Button-1>", scop)
clearb = Button(root, text="C", borderwidth=5,font="Times 20 bold",padx=12,command=lambda: clear())
bkspb = Button(root, text="X",borderwidth=5,font="Times 20 bold",padx=13, command=lambda: bksps())
mod = Button(root, text="mod",borderwidth=5,font="Times 20 bold",padx=0,pady=5,command=lambda: click("%"))
div = Button(root, text="/",borderwidth=5, font="Times 20 bold",padx=18,pady=5,command=lambda: click("/"))
fact = Button(root, text="x!",borderwidth=5,font="Times 20 bold",padx=14,pady=4)
fact.bind("<Button-1>", scop)
seven = Button(root, text="7", borderwidth=5,font="Times 25 bold",padx=10,command=lambda: click("7"))
eight = Button(root, text="8",borderwidth=5, font="Times 25 bold",padx=12,command=lambda: click("8"))
nine = Button(root, text="9",borderwidth=5, font="Times 25 bold",padx=14,command=lambda: click("9"))
mult = Button(root, text="*",borderwidth=5, font="Times 25 bold",padx=10, command=lambda: click("*"))
fraction = Button(root, text="1/x",borderwidth=5,font="Times 20 bold",padx=8,pady=6)
fraction.bind("<Button-1>", scop)
smbo = Button(root, text="(",borderwidth=5, font="Times 25 bold",padx=15,pady=8,command=lambda: click("("))
smbc = Button(root, text=")",borderwidth=5, font="Times 25 bold",padx=15,pady=8,command=lambda: click(")"))
four = Button(root, text="4",borderwidth=5, font="Times 25 bold",padx=10,command=lambda: click("4"))
five = Button(root, text="5", borderwidth=5,font="Times 25 bold",padx=12,command=lambda: click("5"))
six = Button(root, text="6",borderwidth=5, font="Times 25 bold",padx=14,command=lambda: click("6"))
minus = Button(root, text="-", borderwidth=5,font="Times 25 bold",padx=13,command=lambda: click("-"))
one = Button(root, text="1",borderwidth=5,font="Times 25 bold",padx=10,command=lambda: click("1"))
two = Button(root, text="2",borderwidth=5, font="Times 25 bold",padx=12,command=lambda: click("2"))
three = Button(root, text="3", borderwidth=5,font="Times 25 bold",padx=14,command=lambda: click("3"))
plus = Button(root, text="+", borderwidth=5,font="Times 25 bold", padx=9,pady=0,command=lambda: click("+"))
lg = Button(root, text="log",borderwidth=5,font="Times 25 bold", padx=0, pady=0, )
lg.bind("<Button-1>", scop)
zero = Button(root, text="0", borderwidth=5,font="Times 25 bold",padx=12,command=lambda: click("0"))
equal = Button(root, text="=", borderwidth=5,font="Times 25 bold",padx=9,command=lambda: evaluate())
dot = Button(root, text=".", borderwidth=5,font="Times 20 bold",padx=22,pady=6,command=lambda: click("."))
dot.grid(row=7, column=3)
fact.grid(row=6, column=0)
dzero.grid(row=7, column=0)
degree.grid(row=2, column=1)
sin.grid(row=2, column=2)
cos.grid(row=2, column=3)
tan.grid(row=3, column=3)
squrt.grid(row=3, column=0)
clearb.grid(row=3, column=1)
mod.grid(row=4, column=0)
div.grid(row=6, column=4)
bkspb.grid(row=3, column=2)
seven.grid(row=4, column=1)
eight.grid(row=4, column=2)
nine.grid(row=4, column=3)
mult.grid(row=5, column=4)
fraction.grid(row=5, column=0)
four.grid(row=5, column=1)
five.grid(row=5, column=2)
six.grid(row=5, column=3)
minus.grid(row=4, column=4)
one.grid(row=6, column=1)
two.grid(row=6, column=2)
three.grid(row=6, column=3)
plus.grid(row=3, column=4)
lg.grid(row=7, column=1)
zero.grid(row=7, column=2)
equal.grid(row=7, column=4)
smbo.grid(row=2, column=0)
smbc.grid(row=2 , column=4)
root.mainloop()